### ISSUE TITLE
请问，下载失败 也没有提示  啥原因啊。

### ISSUE THREAD

**Issue by onescorpion** [Harlan-H/BiliDownloader#1]
![image](https://user-images.githubusercontent.com/42234804/207368833-7632c7de-9a92-4567-b7be-53cca39cff9f.png)
[](url)

**Comment by Harlan-H** [comment]
鼠标指针放到错误这两个字上 就看到提原因了

**Comment by Harlan-H** [comment]
还有就是 如果你是直接clone得我最新得源码得话 我不能保证 他一定可用  
我只是换了框架 但是我并没有发布这个版本

**Comment by onescorpion** [comment]
> 鼠标指针放到错误这两个字上 就看到提原因了

放到上面 一闪而过。看不清。

**Comment by onescorpion** [comment]
> 还有就是 如果你是直接clone得我最新得源码得话 我不能保证 他一定可用 我只是换了框架 但是我并没有发布这个版本

是的了 直接clone的最新的代码。笑哭

**Comment by onescorpion** [comment]
11
