### ISSUE TITLE
创建批量下载任务后，第一次下载时大量出现"HttpClient.Timeout of 10 seconds elapsing."

### ISSUE THREAD

**Issue by WineYe** [Harlan-H/BiliDownloader#6]
尝试下载一个视频列表（大概200个视频），并行数1，开始下载后感觉有一半左右的视频第一次下载会出现"HttpClient.Timeout of 10 seconds elapsing."错误，重试几次后都能完成。

![error](https://user-images.githubusercontent.com/6338097/235644354-788320bd-454f-4621-8a0d-dc1b2f232eb2.png)

**Comment by MliKiowa** [comment]
https://github.com/Harlan-H/BiliDownloader/blob/a7eace502ae001ea20d56120422ac809220f9011/BiliDownloader/Utils/Http.cs#L29

改大超时时间就行

**Comment by Harlan-H** [comment]
b站下载 其实是一些风控机制的 你下载的视频数量太大了  他就会触发这个机制
正常来说 b站的响应几乎都是毫秒的 10秒完全足够响应 
即使你给超时改的很大 你一样拿不到内容  我记得早期的时候 我测试过 
一般这个时候 最好的办法就是 停止下载 等一会 再下载 就不会出现这个问题
你也可以按照上面这兄弟说的方法 给超时时间改大 或者删掉那段代码都可以
